include("initialization.jl")
include("crossover.jl")
include("mutation.jl")
a = initialize_population(2, 10)
println(a) 
println(size(a)[2])
println(a[1,2])
println(!a[1,2])
mutation_max_n_genes!(a, 1, 5)
println(a)