include("structs.jl")
include("parser.jl")
include("initialization.jl")
include("fitness_function.jl")
include("mutation.jl")
include("../plotter/plots.jl")
include("selection.jl")
include("crossover.jl")

HCP_d = load_home_care_problem("/home/giorgiomelch/BI_AI/workspace/genetic-algorithm/Home_Care_Problem/data/train_0.json")

#individuals = mixed_initialize_population(HCP_d,10, 10)
pop = mixed_initialize_population(HCP_d,10, 10)
#pop = Population(individuals, 10, individuals[1])
println(pop.best_individual.fitness)
update_population_fitness!(pop, HCP_d)
println(pop.best_individual.fitness)
print_individual_routes(pop.best_individual)
